# Generated by Django 4.2.29 on 2026-08-12 14:22

import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def _backfill_n_policy_threshold(apps, schema_editor):
    TaskGroup = apps.get_model('tasks_management', 'TaskGroup')
    TaskGroup.objects.filter(completion_policy='N', threshold__isnull=True).update(threshold=1)


def _reverse_n_policy_threshold(apps, schema_editor):
    TaskGroup = apps.get_model('tasks_management', 'TaskGroup')
    TaskGroup.objects.filter(completion_policy='N', threshold=1).update(threshold=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_management', '0010_add_search_all_perms_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTaskDecision',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical task decision',
                'verbose_name_plural': 'historical task decisions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaskFlow',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', models.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical task flow',
                'verbose_name_plural': 'historical task flows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaskFlowStep',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', models.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('completion_policy', models.CharField(blank=True, choices=[('ALL', 'ALL'), ('ANY', 'ANY'), ('N', 'N')], max_length=50, null=True)),
                ('threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical task flow step',
                'verbose_name_plural': 'historical task flow steps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaskDecision',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskFlow',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', models.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskFlowStep',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', models.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('completion_policy', models.CharField(blank=True, choices=[('ALL', 'ALL'), ('ANY', 'ANY'), ('N', 'N')], max_length=50, null=True)),
                ('threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='historicaltaskgroup',
            name='threshold',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='threshold',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaskexecutor',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaskexecutor',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaskgroup',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaskgroup',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecutor',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecutor',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        # Legacy 'N'-policy groups predate a stored threshold; resolve_task_n
        # was hardcoded to ANY, so threshold=1 preserves behaviour and lets
        # the check constraint below apply to existing rows.
        migrations.RunPython(_backfill_n_policy_threshold, _reverse_n_policy_threshold),
        migrations.AddConstraint(
            model_name='taskgroup',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completion_policy', 'N'), ('threshold__gte', 1)), models.Q(models.Q(('completion_policy', 'N'), _negated=True), ('threshold__isnull', True)), _connector='OR'), name='task_group_threshold_matches_policy'),
        ),
        migrations.AddField(
            model_name='taskflowstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='steps', to='tasks_management.taskflow'),
        ),
        migrations.AddField(
            model_name='taskflowstep',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flow_steps', to='tasks_management.taskgroup'),
        ),
        migrations.AddField(
            model_name='taskflowstep',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskflowstep',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskflow',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskflow',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdecision',
            name='flow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decisions', to='tasks_management.taskflowstep'),
        ),
        migrations.AddField(
            model_name='taskdecision',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decisions', to='tasks_management.task'),
        ),
        migrations.AddField(
            model_name='taskdecision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdecision',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdecision',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskflowstep',
            name='flow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks_management.taskflow'),
        ),
        migrations.AddField(
            model_name='historicaltaskflowstep',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskflowstep',
            name='task_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks_management.taskgroup'),
        ),
        migrations.AddField(
            model_name='historicaltaskflowstep',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskflowstep',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskflow',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskflow',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskflow',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskdecision',
            name='flow_step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks_management.taskflowstep'),
        ),
        migrations.AddField(
            model_name='historicaltaskdecision',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskdecision',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks_management.task'),
        ),
        migrations.AddField(
            model_name='historicaltaskdecision',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskdecision',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaskdecision',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='current_step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks_management.taskflowstep'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='flow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks_management.taskflow'),
        ),
        migrations.AddField(
            model_name='task',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_at_step', to='tasks_management.taskflowstep'),
        ),
        migrations.AddField(
            model_name='task',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tasks_management.taskflow'),
        ),
        # Placed after the flow/current_step AddField operations — the
        # autodetector emits this constraint before the FK fields it
        # references, which fails at apply time.
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('flow__isnull', False), ('current_step__isnull', True), _connector='OR'), name='task_current_step_requires_flow'),
        ),
        migrations.AddConstraint(
            model_name='taskflowstep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('replacement_uuid__isnull', True)), fields=('flow', 'order'), name='unique_task_flow_step_order'),
        ),
        migrations.AddConstraint(
            model_name='taskflowstep',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completion_policy__isnull', True), ('threshold__isnull', True)), models.Q(('completion_policy', 'N'), ('completion_policy__isnull', False), ('threshold__gte', 1)), models.Q(('completion_policy__in', ['ALL', 'ANY']), ('threshold__isnull', True)), _connector='OR'), name='task_flow_step_threshold_matches_policy'),
        ),
        migrations.AddConstraint(
            model_name='taskflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('replacement_uuid__isnull', True)), fields=('code',), name='unique_task_flow_code'),
        ),
        migrations.AddIndex(
            model_name='taskdecision',
            index=models.Index(fields=['task', 'flow_step'], name='idx_task_decision_task_step'),
        ),
        migrations.AddConstraint(
            model_name='taskdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('flow_step__isnull', False), ('is_deleted', False), ('record_id__isnull', False)), fields=('task', 'flow_step', 'user', 'record_id'), name='unique_decision_step_user_record'),
        ),
        migrations.AddConstraint(
            model_name='taskdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('flow_step__isnull', False), ('is_deleted', False), ('record_id__isnull', True)), fields=('task', 'flow_step', 'user'), name='unique_decision_step_user_whole_task'),
        ),
        migrations.AddConstraint(
            model_name='taskdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('flow_step__isnull', True), ('is_deleted', False), ('record_id__isnull', False)), fields=('task', 'user', 'record_id'), name='unique_decision_flat_user_record'),
        ),
        migrations.AddConstraint(
            model_name='taskdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('flow_step__isnull', True), ('is_deleted', False), ('record_id__isnull', True)), fields=('task', 'user'), name='unique_decision_flat_user_whole_task'),
        ),
        migrations.AddConstraint(
            model_name='taskdecision',
            constraint=models.CheckConstraint(check=models.Q(('record_id__isnull', True), models.Q(('record_id', ''), _negated=True), _connector='OR'), name='task_decision_record_id_not_blank'),
        ),
    ]
